<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0sY2OT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0sY2OT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK0sY2OT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK0sY2OT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK0sY2OT\App_KernelDevDebugContainer([
    'container.build_hash' => 'K0sY2OT',
    'container.build_id' => '54fc10bb',
    'container.build_time' => 1646308526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0sY2OT');
