<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSATVE2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSATVE2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSATVE2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSATVE2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSATVE2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'SATVE2x',
    'container.build_id' => 'dfd820bb',
    'container.build_time' => 1646311137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSATVE2x');
