<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWYoaxEy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWYoaxEy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWYoaxEy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWYoaxEy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWYoaxEy\App_KernelDevDebugContainer([
    'container.build_hash' => 'WYoaxEy',
    'container.build_id' => '6d73adca',
    'container.build_time' => 1644692328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWYoaxEy');
