<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\GentleChefController::index'], [], [['text', '/']], [], [], []],
    'story' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showStory'], [], [['text', '/histoire']], [], [], []],
    'team' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showTeam'], [], [['text', '/equipe']], [], [], []],
    'movies' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showMovies'], [], [['text', '/films']], [], [], []],
    'movie' => [['id'], ['_controller' => 'App\\Controller\\GentleChefController::showMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/film']], [], [], []],
    'studies' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showStudies'], [], [['text', '/etudes']], [], [], []],
    'study' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showStudy'], [], [['text', '/etude']], [], [], []],
    'news' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showNews'], [], [['text', '/actualites']], [], [], []],
    'new' => [['id'], ['_controller' => 'App\\Controller\\GentleChefController::showNew'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/actualite']], [], [], []],
    'support' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showSupport'], [], [['text', '/soutenir']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\GentleChefController::showContact'], [], [['text', '/contact']], [], [], []],
];
